spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.goazwmbvraoengmetdpy
spring.datasource.password=f3qCjViqbpfrg1Hz
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update # Consider 'validate' or 'none' for production after initial setup
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Ensure this matches the default naming strategy if you have specific needs
# spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JWT Configuration
supabase.jwt.secret=Qiopu5BdnmUj2YJ0/JvEuqrnpIM3QKBnRYx0ozGfpi+OW5ULPrdG9MPfYZjn9AphRxNmWJQbacey8iKJQIy5pg==
# jwt.expiration.ms can be added here if different from dev/default
